version: '3.9'

services:
  rsauth:
    container_name: rsauth
    image: rsauth
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7100:80"
    depends_on: [redis]

  redis:
    container_name: rsauth-redis
    image: redis
    ports:
      - "7101:6379"
    volumes:
      - redis:/data

networks:
  default:
    name: rsnetwork

volumes:
  redis:
    external: false