version: '3.9'

services:
  rsstorage:
    container_name: rsstorage
    image: rsstorage
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7400:80"
    depends_on: [redis]

  redis:
    container_name: rsstorage-redis
    image: redis
    ports:
      - "7401:6379"
    volumes:
      - redis:/data

networks:
  default:
    name: rsnetwork

volumes:
  redis:
    external: false