version: '3.9'

services:
  rscontent:
    container_name: rscontent
    image: rscontent
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7500:80"
    depends_on: [redis]

  redis:
    container_name: rscontent-redis
    image: redis
    ports:
      - "7501:6379"
    volumes:
      - redis:/data

networks:
  default:
    name: rsnetwork

volumes:
  redis:
    external: false