version: '3.9'

services:
  rscontact:
    container_name: rscontact
    image: rscontact
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7300:80"
    depends_on: [redis]

  redis:
    container_name: rscontact-redis
    image: redis
    ports:
      - "7301:6379"
    volumes:
      - redis:/data

networks:
  default:
    name: rsnetwork
volumes:
  redis:
    external: false